### ISSUE TITLE
Add feature: checklists

### ISSUE THREAD

**Issue by ttx** [wefork/wekan#11]
Checklists are one of the most obvious gaps between Wekan and Trello.

There is a checklist implementation stuck in the original Wekan pull requests: https://github.com/wekan/wekan/pull/630 -- consider adding it to the fork ?

**Comment by ocdtrekkie** [comment]
I agree this PR should be one of the top priorities for the maintainers of the fork. It would be good particularly to ensure features offered up in the PRs from the original Wekan repo should be properly reviewed by the folks here, tested, and then the first stable "release" of the forked version should be published.

Perhaps @lkisme should reopen the PR against this repo, so that they can handle any needed rebasing on any changes since.

**Comment by xet7** [comment]
@ttx @ocdtrekkie 

I added this to wefork roadmap.

**Comment by xet7** [comment]
Merged.
