### ISSUE TITLE
Add feature: due dates

### ISSUE THREAD

**Issue by ttx** [wefork/wekan#12]
Due dates (or deadlines) are the second most obvious gap between Trello and Wekan.

There is an implementation for that stuck in the original repository pull requests: https://github.com/wekan/wekan/pull/517 -- Consider adding it to the fork.

**Comment by ocdtrekkie** [comment]
I agree this PR should be one of the top priorities for the maintainers of the fork. It would be good particularly to ensure features offered up in the PRs from the original Wekan repo should be properly reviewed by the folks here, tested, and then the first stable "release" of the forked version should be published.

Perhaps @shoetten should reopen the PR against this repo, so that they can handle any needed rebasing on any changes since.

**Comment by xet7** [comment]
@ttx @ocdtrekkie 

I added this to wefork roadmap.

**Comment by shoetten** [comment]
Hey everyone, good to see some work happening on the project.

I can definitely reopen my PR against this repo and make some improvements to it. But it was some time ago, when i originally build this and i don't have as much time right now as i had back then.

What do you think about opening a new branch for the due date functionality, where you merge my work in? That way somebody else could take over, especially with the integration into the activities / notifications feed.
Or if you want to have it in devel asap, i can target that as well and activity feed integration (and any other improvements) could come at a later stage.

**Comment by xet7** [comment]
@shoetten 

Hi,
- minimal implementation would be enough, pull request to devel branch. I can test it from there directly, and @dwrensha can make sure it's turned off for Sandstorm.
- it would be nice that when importing from Trello, due dates could be imported too.

Activity feed status currently:
- Sandstorm has it's own Sandstorm-specific activity feed
- Wefork has in-progress work of @mario-orlicky of issue https://github.com/wekan/wekan/issues/683 to add settings option to hide system messages in the card, so activity feed is less noisy.

So activity feed setup option and others can come later.

**Comment by dwrensha** [comment]
> I can test it from there directly, and @dwrensha can make sure it's turned off for Sandstorm.

...

> Sandstorm has it's own Sandstorm-specific activity feed

To clarify: Wekan's activity feed is still enabled in the Sandstorm package. Wekan activity events are forwarded to Sandstorm. Wekan _notifications_ are disabled, as Sandstorm is responsible for mapping activity events into notifications.

It looks like the due dates feature would add some new kinds of activity events. We would need to declare them [here](https://github.com/wefork/wekan/blob/33913cf1ce9b5971144802060d1169143d2fec6b/sandstorm-pkgdef.capnp#L179-L216) so that Sandstorm knows about them.

**Comment by xet7** [comment]
@dwrensha 

I happened to merge this implementation, that works on standalone Wekan:
https://github.com/wefork/wekan/pull/26

Does this affect Sandstorm someway?

**Comment by dwrensha** [comment]
The feature will be available in the Sandstorm package. It seems to work fine.
