### ISSUE TITLE
Add to wiki: Creating Sandstorm .spk from Wekan source

### ISSUE THREAD

**Issue by xet7** [wefork/wekan#36]
Add to wiki, how to create wekan.spk from source, so it can be installed to Sandstorm instance and tested there.

I have not looked are there instructions somewhere already, so if there is, this can be closed with link to existing documentation.

**Comment by ocdtrekkie** [comment]
This should be relatively trivial to document. You pretty much just run `spk pack` in the source folder. (Though it might be `meteor-spk pack` actually, which would need to be installed, as well as Sandstorm itself.)

The important part is that a third party trying to build it will not have the required key to publish an app with the Wekan app ID. They would need to change it, which is a process documented here: https://docs.sandstorm.io/en/latest/developing/publishing-apps/#double-check-your-app-id

And they could not upgrade grains from official Wekan to a Wekan version they built themselves.

**Comment by dwrensha** [comment]
@ocdtrekkie Unfortunately it's not quite so simple.

Due to https://github.com/sandstorm-io/meteor-spk/issues/25, a locally-modified version of meteor-spk v0.2.1 needs to be used (updated schemas need to be dropped in at `meteor-spk.deps/node_modules/sandstorm/`).

Due to the issue described [here](https://github.com/sandstorm-io/meteor-accounts-sandstorm/pull/31), I've been maintaining an [upstream patch](https://github.com/dwrensha/wekan/commit/f2fe28aed74b265b66a86a031a9c8b7bf6bcc41e) in Wekan that I apply before releasing.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/823
